#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

# THE WIDGET SECTION OF docs/MODULES.md IS GENERATED, AND MUST NOT DRIFT.
#
# It is the one place that puts each widget's picture next to the rule that
# selects it, and both halves are derived from the shipping code — so a widget
# change silently invalidates it. Documentation that is confidently wrong is
# worse than none, because it is what the next person reads instead of the
# render.
#
# It lives INSIDE a hand-written document, between markers, which is why the
# generator splices rather than overwrites. The user-facing subset in
# ../schwung-catalog-site/manual.html is generated by the same tool with
# --manual, and is NOT checked here: that repo is optional.
#
# So the generator has a --check mode: it rebuilds the markdown and every
# swatch into memory and byte-compares. Change a widget and this fails with
# the command that fixes it.
#
# This is the same bargain as tests/fixtures/movy-geom-baseline.txt — a
# deliberate refresh is a reviewed diff, and an accidental one is a red test.
# It is stricter than the baseline in one way that matters: the baseline pins
# hashes, so a changed picture tells you only THAT it changed. Here the diff
# is the PNG itself and the prose beside it, so the review is the picture.

if ! command -v node >/dev/null 2>&1; then
  echo "FAIL: node is required for the widget sheet check" >&2
  exit 1
fi

if ! command grep -q "BEGIN generated widgets" docs/MODULES.md; then
  echo "FAIL: the generated-widgets markers are missing from docs/MODULES.md" >&2
  exit 1
fi

# The generator prints its own failure, naming every stale file.
node tools/param-pages/widget_sheet.mjs --check

# --- the check must be able to FAIL -----------------------------------------
#
# A --check that passes unconditionally is the failure mode this whole file
# exists to prevent, and it is invisible: it prints PASS either way. So prove
# it by corrupting a byte of the committed markdown, re-running, and requiring
# a non-zero exit. Restored from a copy rather than regenerated, so a broken
# generator cannot leave the tree modified.
# mktemp, not $TMPDIR: it is unset on the CI runner, and "$TMPDIR/x" would
# then write to /x and fail the test for a reason unrelated to widgets.
BACKUP="$(mktemp)"
cp docs/MODULES.md "$BACKUP"
restore() { cp "$BACKUP" docs/MODULES.md; rm -f "$BACKUP"; }
trap restore EXIT

# Corrupt INSIDE the generated block, not at the end of the file: appending
# past the END marker changes a byte the splice never compares, so the check
# would rightly pass and the mutation would prove nothing.
perl -pi -e 's/\Qarc knob\E/arc knobb/ if $. < 2000' docs/MODULES.md
if node tools/param-pages/widget_sheet.mjs --check >/dev/null 2>&1; then
  echo "FAIL: --check passed on a corrupted widget section — it is not comparing anything" >&2
  exit 1
fi
restore
trap - EXIT

echo "  ok  --check detects a stale section"
echo "PASS: docs/MODULES.md matches the widgets it documents"
