/**
 * widget_gen.mjs — sprite rows + a widget spec  ->  a module's widgets.mjs.
 *
 * THE NO-JS PATH IS A BUILD STEP, NOT A RUNTIME FORMAT.
 *
 * A C-only author describes their frames beside their art and runs this. They
 * never write JavaScript, exactly as they never write ARM assembly to get a
 * dsp.so. The declarative tier still exists -- it just runs on THEIR machine,
 * so a malformed sprite config is a red build for the person who wrote it
 * rather than a broken widget for whoever installed the module.
 *
 * Nothing new ships to the device as a result: no parser, no runtime
 * validator, no second file format to version.
 *
 * IT LIVES IN THIS REPO, beside widget_sheet.mjs, for LOCKSTEP rather than
 * convenience -- the runtime consumes this output, so a runtime change that
 * breaks the format has to fail in this repo's CI, not silently in an author's
 * build weeks later. A build step that can drift without failing defeats every
 * bisect that follows it.
 *
 * Usage:
 *   node tools/param-pages/widget_gen.mjs widgets.json > widgets.mjs
 *
 * Spec shape:
 *   {
 *     "kind": "custom:mymeter",
 *     "nominal": { "w": 17, "h": 15 },
 *     "frames": [
 *       { "atMost": 0.33, "rows": ["#####...", ...] },
 *       { "atMost": 1.00, "rows": ["########", ...] }
 *     ]
 *   }
 *
 * `rows` is "#" set, anything else clear -- the same shape spriteFromRows takes,
 * so a hand-written sprite and a generated one are the same thing. A PNG is
 * converted to rows by whatever the author's build already has; this tool
 * deliberately does not decode images, because pulling an image decoder into
 * the repo to read 1-bit art would be the largest dependency here by far.
 */

const CUSTOM_PREFIX = "custom:";

function runsFromRows(rows) {
    const h = rows.length;
    const w = h ? rows[0].length : 0;
    const runs = [];
    for (let y = 0; y < h; y++) {
        let x = 0;
        while (x < w) {
            if (rows[y][x] !== "#") { x++; continue; }
            let end = x;
            while (end < w && rows[y][end] === "#") end++;
            runs.push([x, y, end - x]);
            x = end;
        }
    }
    return { w, h, runs };
}

/**
 * @param {object} spec  { kind, nominal: {w,h}, frames: [{atMost, rows}] }
 * @returns {string} the text of a widgets.mjs
 */
export function generate(spec) {
    if (!spec || typeof spec.kind !== "string" || !spec.kind.startsWith(CUSTOM_PREFIX)) {
        throw new Error(
            `widget kind must start with "${CUSTOM_PREFIX}": got ${spec && spec.kind}`);
    }
    const nominal = spec.nominal || {};
    const nw = nominal.w, nh = nominal.h;
    if (!(nw > 0 && nh > 0)) {
        throw new Error("the spec must declare a nominal w and h");
    }
    if (!Array.isArray(spec.frames) || spec.frames.length === 0) {
        throw new Error("the spec declares no frames");
    }

    const frames = spec.frames.map((f, i) => {
        const rows = f.rows;
        if (!Array.isArray(rows) || rows.length === 0) {
            throw new Error(`frame ${i} has no rows`);
        }
        const fh = rows.length, fw = rows[0].length;
        if (rows.some((r) => r.length !== fw)) {
            throw new Error(`frame ${i} has ragged rows`);
        }
        /* THE BUILD-TIME CHECK. Catching this here is the entire argument for
         * the generator existing: the author sees it, the user never does. It
         * cannot be fixed at runtime, because 1-bit art is never rescaled. */
        if (fw !== nw || fh !== nh) {
            throw new Error(
                `frame ${i} is ${fw}x${fh} but nominal is ${nw}x${nh} — every ` +
                `frame must match the nominal frame exactly (1-bit art is never ` +
                `rescaled, so a mismatched frame cannot be corrected at runtime)`);
        }
        if (typeof f.atMost !== "number") {
            throw new Error(`frame ${i} has no numeric atMost threshold`);
        }
        return { atMost: f.atMost, sprite: runsFromRows(rows) };
    });

    /* Sorted so the runtime lookup can stop at the first match, and so two
     * specs listing the same frames in a different order generate the same
     * file. */
    frames.sort((a, b) => a.atMost - b.atMost);

    const framesLit = frames.map((f) =>
        `    { atMost: ${f.atMost}, runs: ${JSON.stringify(f.sprite.runs)} },`).join("\n");

    return `/* GENERATED by tools/param-pages/widget_gen.mjs — do not edit.
 *
 * Re-generate with:
 *   node tools/param-pages/widget_gen.mjs <spec>.json > widgets.mjs
 *
 * Runs, not pixels: a QuickJS binding is ~490ns and a page holds eight knob
 * boxes, so per-pixel blitting would cost ~1ms of a 1.68ms page render.
 */

export const widgetKind = ${JSON.stringify(spec.kind)};
export const widgetNominal = { w: ${nw}, h: ${nh} };

const FRAMES = [
${framesLit}
];

/* Frame-local coordinates only — the ctx cannot express a screen pixel, and
 * carries no getParam: values arrive as an argument. */
export function drawCell(ctx, { values, group }) {
    const key = group && group.keys && group.keys[0];
    const raw = key && values ? Number(values[key]) : 0;
    const v = Number.isFinite(raw) ? raw : 0;

    let frame = FRAMES[FRAMES.length - 1];
    for (const f of FRAMES) { if (v <= f.atMost) { frame = f; break; } }

    /* Refuse rather than rescale: a frame too small for the nominal art gets
     * nothing from us, and the host falls back to the built-in widget. */
    if (ctx.width < widgetNominal.w || ctx.height < widgetNominal.h) return;

    const ox = Math.floor((ctx.width - widgetNominal.w) / 2);
    const oy = Math.floor((ctx.height - widgetNominal.h) / 2);
    for (const [x, y, len] of frame.runs) ctx.fillRect(ox + x, oy + y, len, 1, 1);
}
`;
}

/* CLI. Guarded so importing this module for tests does not read argv. */
if (process.argv[1] && process.argv[1].endsWith("widget_gen.mjs")) {
    const path = process.argv[2];
    if (!path) {
        console.error("usage: node tools/param-pages/widget_gen.mjs <spec>.json > widgets.mjs");
        process.exit(2);
    }
    const { readFileSync } = await import("node:fs");
    try {
        process.stdout.write(generate(JSON.parse(readFileSync(path, "utf8"))));
    } catch (e) {
        console.error(`widget_gen: ${e.message}`);
        process.exit(1);
    }
}
