/*
 * SysEx Test — both directions of the cable-2 SysEx path, on real hardware.
 *
 * The two failures this exists to separate look identical from the outside:
 * a message that never left, and a message that left with a run of packets
 * missing from the middle. Neither raises an error, and a truncated SysEx is
 * still well-framed, so "it didn't work" is all a user can report.
 *
 * So both directions are checked against the SAME generator. Whatever is sent
 * can be regenerated byte-for-byte, which turns "short" into a byte count and
 * a first-bad offset — and an offset divisible by 3 is the signature of whole
 * USB-MIDI packets going missing rather than arbitrary truncation.
 *
 * RIG: Mac <-> Move USB-C "Ableton Move Standalone Port". Measured 2026-08-31:
 * USB-C MIDI lands in the SPI mailbox on CABLE 2, the same cable as USB-A, and
 * only via that one of Move's four ports. So this needs no external MIDI gear.
 *
 * Pads (bottom row) pick the payload size. 158 bytes is the QY-70 bulk-dump
 * message from #358; 632 is deliberately past the outbound carry's high water
 * so the backpressure path gets exercised rather than just the happy one.
 */
import { shouldFilterMessage, setLED } from '/data/UserData/schwung/shared/input_filter.mjs';
import { Black, DullGreen, DarkGreen } from '/data/UserData/schwung/shared/constants.mjs';

/* The display API for a tool module is clear_screen / print / draw_line /
 * fill_rect (registered in src/host/js_display.c), and the host flushes for
 * you. There is no display_text, no display_clear and no host_flush_display --
 * an earlier draft of this file invented all three, and the first tick threw a
 * ReferenceError, which the host reports by unloading the module. On screen
 * that is indistinguishable from "the tool opened and immediately closed",
 * with nothing in the log naming the missing symbol.
 *
 * setLED's second argument is a COLOUR BYTE, not a name. It becomes data2 of a
 * note-on, so a string lands on the wire as garbage rather than raising
 * anything. Import the constants. */

const SIZES = [64, 158, 316, 632];
const PADS = [68, 69, 70, 71];

/* Non-commercial / prototype manufacturer ID. Nothing on the wire acts on it,
 * which matters when the rig is a shared USB bus. */
const MFR = 0x7D;

/* ==================== the generator, used by BOTH directions ==================== */

/* Body byte at index i. A 7-bit counter, so every byte names its own position
 * mod 128 — a missing run shifts everything after it and shows up immediately.
 * The aligned 00 00 00 at 60..62 is deliberate: it lands on a packet boundary
 * (the F0 + 2 header bytes are 3, so body offset 0 is aligned), which is
 * exactly the packet #355 used to drop. If that regresses, this run vanishes
 * and the first-bad offset is 60. */
function bodyByte(i) {
    if (i >= 60 && i <= 62) return 0x00;
    return i & 0x7F;
}

function buildMessage(nbody) {
    const m = [0xF0, MFR, 0x01];
    for (let i = 0; i < nbody; i++) m.push(bodyByte(i));
    m.push(0xF7);
    return m;
}

/* Flat 4-byte USB-MIDI packets, concatenated — what move_midi_external_send
 * actually takes. Not raw SysEx bytes; handing it those sends garbage. */
function packetize(bytes) {
    const out = [];
    let i = 0;
    while (i < bytes.length) {
        const remain = bytes.length - i;
        if (remain > 3)       { out.push(0x04, bytes[i], bytes[i + 1], bytes[i + 2]); i += 3; }
        else if (remain === 3){ out.push(0x07, bytes[i], bytes[i + 1], bytes[i + 2]); i += 3; }
        else if (remain === 2){ out.push(0x06, bytes[i], bytes[i + 1], 0);            i += 2; }
        else                  { out.push(0x05, bytes[i], 0, 0);                       i += 1; }
    }
    return out;
}

/* ==================== state ==================== */

let sizeIdx = 1;                  /* 158 bytes */
let txBytes = 0, txPackets = 0, txRefused = 0;
let rxBytes = 0, rxExpected = 0, rxFirstBad = -1, rxVerdict = "-";
let rxMessages = 0;

/* Inbound assembler. onMidiMessageExternal hands over three bytes at a time
 * with the CIN ALREADY STRIPPED, so there is no length field to trust — the
 * trailing bytes of an end-packet are padding. F7 is the only terminator. */
let asm = null;

function rxByte(b) {
    if (b === 0xF0) { asm = []; return; }
    if (asm === null) return;
    if (b === 0xF7) { finishMessage(); asm = null; return; }
    /* Realtime (F8..FF) legitimately interleaves mid-SysEx and is not ours. */
    if (b >= 0xF8) return;
    /* Any other status byte means our message was interrupted; splicing what
     * follows onto it would produce a plausible-looking third message. */
    if (b >= 0x80) { asm = null; return; }
    if (asm.length < 4096) asm.push(b);
}

function finishMessage() {
    rxMessages++;
    /* asm holds MFR, 0x01, then the body. */
    const body = asm.slice(2);
    rxBytes = asm.length + 2;                 /* + F0 F7, for a wire-byte count */
    rxFirstBad = -1;
    for (let i = 0; i < body.length; i++) {
        if (body[i] !== bodyByte(i)) { rxFirstBad = i; break; }
    }
    /* We do not know which size the sender chose, so score against the nearest
     * declared size rather than inventing one. */
    rxExpected = 0;
    for (const s of SIZES) if (Math.abs(s - body.length) < Math.abs(rxExpected - body.length)) rxExpected = s;

    if (rxFirstBad < 0 && body.length === rxExpected) rxVerdict = "INTACT";
    else if (rxFirstBad < 0) rxVerdict = "SHORT-TAIL";
    else rxVerdict = (rxFirstBad % 3 === 0) ? "LOST PKTS" : "CORRUPT";
}

/* ==================== send ==================== */

function sendOne() {
    const msg = buildMessage(SIZES[sizeIdx]);
    const pkts = packetize(msg);
    txBytes = msg.length;
    txPackets = pkts.length / 4;
    txRefused = 0;

    /* ONE call, deliberately. Pacing it here would hide the very thing under
     * test: whether the host carries a burst it cannot place in one frame, or
     * silently discards the tail. A module author writing an editor sends the
     * whole dump and moves on, so that is what gets measured. */
    const ok = move_midi_external_send(pkts);
    if (!ok) txRefused = 1;
}

/* ==================== lifecycle ==================== */

let ledInitPending = true;
let ledInitIndex = 0;

globalThis.init = function () {
    ledInitPending = true;
    ledInitIndex = 0;
};

function setupLedBatch() {
    for (let n = 0; n < 8 && ledInitIndex < 64; n++, ledInitIndex++) {
        const note = 68 + ledInitIndex;
        const isSize = PADS.indexOf(note) >= 0;
        setLED(note, isSize ? (PADS[sizeIdx] === note ? DullGreen : DarkGreen) : Black);
    }
    if (ledInitIndex >= 64) ledInitPending = false;
}

function refreshSizeLeds() {
    for (let i = 0; i < PADS.length; i++) {
        setLED(PADS[i], i === sizeIdx ? DullGreen : DarkGreen);
    }
}

globalThis.onMidiMessageInternal = function (data) {
    if (shouldFilterMessage(data)) return;
    const status = data[0] & 0xF0;
    const d1 = data[1], d2 = data[2];

    if (status === 0x90 && d2 > 0) {
        const idx = PADS.indexOf(d1);
        if (idx >= 0) { sizeIdx = idx; refreshSizeLeds(); return; }
        /* Any other pad sends, so the size row stays a selector. */
        if (d1 >= 72 && d1 <= 99) sendOne();
    }
};

globalThis.onMidiMessageExternal = function (data) {
    /* Three bytes, CIN stripped. Feed all three; the assembler ignores the
     * padding an end-packet carries. */
    rxByte(data[0]); rxByte(data[1]); rxByte(data[2]);
};

globalThis.tick = function () {
    if (ledInitPending) { setupLedBatch(); return; }
    draw();
};

function draw() {
    clear_screen();
    print(2, 0, "SysEx Test", 2);
    draw_line(0, 13, 127, 13, 1);

    print(2, 16, "size " + SIZES[sizeIdx] + "B", 1);
    print(2, 26, "tx " + txBytes + "B/" + txPackets + "p" +
                        (txRefused ? " REFUSED" : ""), 1);

    print(2, 36, "rx " + rxBytes + "B  n=" + rxMessages, 1);
    print(2, 46, rxVerdict + (rxFirstBad >= 0 ? " @" + rxFirstBad : ""), 1);

    print(2, 56, "pad1-4=size rest=send", 1);
}
