/*
 * SysEx Test — both directions of the cable-2 SysEx path, on real hardware.
 *
 * The two failures this exists to separate look identical from the outside:
 * a message that never left, and a message that left with a run of packets
 * missing from the middle. Neither raises an error, and a truncated SysEx is
 * still well-framed, so "it didn't work" is all a user can report.
 *
 * So both directions are checked against the SAME generator. Whatever is sent
 * can be regenerated byte-for-byte, which turns "short" into a byte count and
 * a first-bad offset — and an offset divisible by 3 is the signature of whole
 * USB-MIDI packets going missing rather than arbitrary truncation.
 *
 * RIG: Mac <-> Move USB-C "Ableton Move Standalone Port". Measured 2026-08-31:
 * USB-C MIDI lands in the SPI mailbox on CABLE 2, the same cable as USB-A, and
 * only via that one of Move's four ports. So this needs no external MIDI gear.
 *
 * Pads (bottom row) 1-4 pick the payload size. 158 bytes is the QY-70 bulk-dump
 * message from #358; 632 is deliberately past the outbound carry's high water
 * so the backpressure path gets exercised rather than just the happy one.
 *
 *   1-4  payload size          5  send /data/UserData/schwung/sysex_send.txt
 *   6    E16 ENTER remote      7  E16 EXIT remote
 *   8    E16 OLED LABELS       9  E16 LED RING
 *   10   Program Change        11 plain CC
 *   12   ENTER as CIN 0x0F     13 LABELS as CIN 0x0F
 *   14   ENTER, every packet CIN 0x07
 *   15   probe: F0 F7 in one CIN 0x06 packet
 *   16+  send the generated payload
 *
 * Pads 8 and 9 are the ones that answer "did remote mode engage" without
 * relying on anything coming back: they change what is on the E16's own
 * screen and rings. The ACK is the better evidence when it arrives, but it is
 * inbound SysEx and so reaches JS only in overtake mode -- which this module
 * is, and a chain slot is not.
 */
import { shouldFilterMessage, setLED } from '/data/UserData/schwung/shared/input_filter.mjs';
import { Black, DullGreen, DarkGreen } from '/data/UserData/schwung/shared/constants.mjs';

/* The display API for a tool module is clear_screen / print / draw_line /
 * fill_rect (registered in src/host/js_display.c), and the host flushes for
 * you. There is no display_text, no display_clear and no host_flush_display --
 * an earlier draft of this file invented all three, and the first tick threw a
 * ReferenceError, which the host reports by unloading the module. On screen
 * that is indistinguishable from "the tool opened and immediately closed",
 * with nothing in the log naming the missing symbol.
 *
 * setLED's second argument is a COLOUR BYTE, not a name. It becomes data2 of a
 * note-on, so a string lands on the wire as garbage rather than raising
 * anything. Import the constants. */

const SIZES = [64, 158, 316, 632];
const PADS = [68, 69, 70, 71];

/* Pad 5 sends whatever hex is in this file, instead of a generated payload.
 *
 * A file rather than a hardcoded constant because the message under test is
 * usually one nobody here can verify. The case this was built for: putting an
 * OXI E16 into remote mode, whose SysEx spec is published only in a Google
 * Sheet that is now private -- so the bytes have to come from whoever has
 * them, and baking in a guess would produce a test that looks like it passes
 * while sending something meaningless.
 *
 * Format is forgiving on purpose: whitespace, newlines, commas and 0x prefixes
 * are all fine, and a # starts a comment. Include the F0 and F7 -- they are
 * ordinary bytes to the packetizer.
 *
 *   echo 'F0 00 21 5D 01 ... F7' > /data/UserData/schwung/sysex_send.txt
 */
const CUSTOM_PATH = "/data/UserData/schwung/sysex_send.txt";
const CUSTOM_PAD = 72;

/* ---- OXI E16 remote mode -------------------------------------------------
 *
 * From OXI's own "OXI REMOTE" spec sheet, E16 tab. Header f0 00 21 5b 02 01,
 * then a two-byte message ID, then F7. ENTER and its ACK carry no payload.
 *
 * THE ACK IS WHY THIS PAD EXISTS. "Did the message go out" is answerable by
 * the shim's PRE tap already; what nobody could answer is whether the DEVICE
 * received it. The E16 answers 0x06 0x53 to acknowledge entering remote mode,
 * so a round trip is observable and the pad reports RX rather than TX.
 *
 * That reply is inbound SysEx, which reaches JS only in overtake mode -- this
 * module is an overtake tool, so it sees it. The same message sent from a
 * chain slot would go out fine and the ACK would never arrive, which is
 * exactly the "sends fine, never answers" shape in docs/SYSEX.md.
 */
const OXI_HDR = [0x00, 0x21, 0x5B, 0x02, 0x01];
const OXI_ENTER = [0xF0].concat(OXI_HDR, [0x06, 0x55], [0xF7]);
const OXI_EXIT  = [0xF0].concat(OXI_HDR, [0x06, 0x00], [0xF7]);
const OXI_ACK_ID = [0x06, 0x53];
const OXI_PAD = 73;
const OXI_EXIT_PAD = 74;
const OXI_LABELS_PAD = 75;
const OXI_RING_PAD = 76;

/* Pads 10 and 11 send NON-SysEx to the same device, and that is the point.
 *
 * Every outbound figure in docs/SYSEX.md was measured over USB-C with Move as
 * a USB DEVICE. Sending TO a device on USB-A, where Move is the HOST, is a
 * different XMOS path and has never been verified -- for SysEx or for anything
 * else. So "our SysEx does not arrive" has two readings, and nothing we have
 * measured separates them: SysEx specifically is not forwarded on the host
 * path, or NOTHING is.
 *
 * A Program Change is the discriminator, because the E16 acts on one without
 * being in remote mode: Settings > MIDI > PC Receive Channel, then PC 1-16
 * selects the scene, visibly, on the device's own screen. If the scene changes
 * the host path forwards fine and the fault is SysEx-shaped. If it does not,
 * nothing we send reaches USB-A at all and remote mode was never the problem.
 *
 * CC is here too because it is the one thing the MiniLab proved works INBOUND
 * on this port, so it isolates direction from message type. */
const PC_PAD = 77;
const CC_PAD = 78;
let pcProgram = 0;

/* Pads 12 and 13 send the SAME SysEx bytes with a different CIN, and that is
 * the whole experiment.
 *
 * Measured 2026-09-09 on this device: a plain CC (CIN 0x0B) reaches an E16 on
 * USB-A and moves its LED ring, while the identical mailbox carrying SysEx
 * (CIN 0x04/0x07) produces nothing -- no ACK, no screen change, nothing. Same
 * cable, same frame, same slots, verified byte-for-byte in the shim's POSThw
 * tap. So the XMOS's USB-HOST transmit path appears not to forward the SysEx
 * CINs at all, which is the outbound sibling of the inbound losses in #358.
 *
 * CIN 0x0F is "single byte, unparsed" -- one data byte per packet, no message
 * structure implied. An implementation that drops 0x04-0x07 may still forward
 * these, because they need no reassembly logic to pass along. If it does, a
 * SysEx sent one byte per packet arrives intact and remote mode is reachable
 * from the Move after all.
 *
 * It costs 4 wire bytes per payload byte, so ENTER is 9 packets and LABELS is
 * 101 -- under the 128-per-flush ceiling, and the carry keeps them in order.
 * If this works it is a transport quirk to hide in one helper, not a thing
 * every module author should have to know. */
const OXI_ENTER_F_PAD = 79;
const OXI_LABELS_F_PAD = 80;

/* ---- CIN 0x04 is the suspect ---------------------------------------------
 *
 * Read off the E16's OWN monitor, 2026-09-09, which is the first instrument
 * either side of this has had on the receiving end:
 *
 *   pad 11 (CC, CIN 0x0B)    -> "USB CH1: CC1 64"      complete and correct
 *   pad 6  (SysEx)           -> empty messages
 *   pad 12 (CIN 0x0F)        -> "USB SYSEX END"
 *
 * Both failures show a SysEx END and no content. The bytes are arriving, so
 * the XMOS transmits on the USB-host path -- but whatever carries the F0 and
 * the middle bytes is being lost, and that is CIN 0x04, "SysEx starts or
 * continues". The terminating CINs (0x05/0x06/0x07) evidently get through,
 * which is why the device sees a tail with nothing in front of it.
 *
 * Channel-voice messages are immune because they are a single packet with
 * their own CIN, which is why CC and Program Change both work.
 *
 * PAD 14 tests the workaround: send EVERY packet as CIN 0x07 (ends with three
 * bytes). Each is forwarded, and the device receives the correct byte stream
 * F0 00 21 / 5B 02 01 / 06 55 F7 in order. It is malformed as USB-MIDI -- three
 * "message ends" in a row -- but most devices reassemble SysEx from the byte
 * stream rather than trusting CINs, so it may simply work.
 *
 * PAD 15 confirms the diagnosis instead of assuming it: F0 F7 alone is a legal
 * two-byte SysEx that fits in ONE CIN 0x06 packet, with no 0x04 anywhere. If
 * the monitor shows that arriving while pad 6 does not, CIN 0x04 is proven to
 * be the one being dropped, and this stops being a theory.
 *
 * It only requires the message length to be a multiple of 3 -- pad 14 says so
 * rather than silently sending a bad tail. */
const OXI_ENTER_7_PAD = 81;
const OXI_PROBE_PAD = 82;

/* Every packet CIN 0x07, three payload bytes each. */
function packetizeAllEnds(bytes) {
    const out = [];
    for (let i = 0; i + 2 < bytes.length; i += 3) {
        out.push(0x07, bytes[i], bytes[i + 1], bytes[i + 2]);
    }
    return out;
}

function sendOxiAllEnds(msg, label) {
    customNote = "";
    if (msg.length % 3 !== 0) {
        oxiState = label + " len%3!=0";
        return;
    }
    const pkts = packetizeAllEnds(msg);
    txBytes = msg.length;
    txPackets = pkts.length / 4;
    txRefused = move_midi_external_send(pkts) ? 0 : 1;
    oxiState = txRefused ? (label + " REFUSED") : (label + " sent, waiting ACK");
    if (!txRefused) oxiSentAt = ticks;
}

/* One CIN 0x0F packet per byte, cable nibble left at 0 for the host to set. */
function packetizeSingleBytes(bytes) {
    const out = [];
    for (let i = 0; i < bytes.length; i++) {
        out.push(0x0F, bytes[i], 0x00, 0x00);
    }
    return out;
}

function sendOxiSingle(msg, label) {
    customNote = "";
    const pkts = packetizeSingleBytes(msg);
    txBytes = msg.length;
    txPackets = pkts.length / 4;
    txRefused = move_midi_external_send(pkts) ? 0 : 1;
    if (txRefused) {
        oxiState = label + " REFUSED";
    } else {
        oxiState = label + " sent, waiting ACK";
        oxiSentAt = ticks;
    }
}

/* The rest of the spec, which the first version of this file could not get.
 *
 * The sheet is not private -- the forum preview says so because it fetches it
 * unauthenticated, and it EXPORTS:
 *
 *   curl -sL "https://docs.google.com/spreadsheets/d/\
 *     1Yccnrluv10QL_PauMmtCt64EtYjfSeZEXKrlrw8P24w/export?format=csv&gid=1057524829"
 *
 *   06 01  LED           5-byte chunks: enc 0-15, led 0-15, R, G, B (0-127)
 *   06 02  FRAMEBUFFER   1024 raw bytes, SSD1306 page/column, 128x64
 *   06 03  LABELS        80 raw: 16-char title + 16 x 4-char label
 *   06 04  LED RING      7-byte chunks: enc, R, G, B, amt MSB, amt LSB, bipolar
 *
 * FRAMEBUFFER and LABELS override each other; the framebuffer is whole-screen
 * only. Note the geometry -- 128x64 mono is Move's own display, so mirroring a
 * Schwung page onto an E16 is a packer, not a renderer.
 */
const OXI_ID_LABELS = [0x06, 0x03];
const OXI_ID_RING   = [0x06, 0x04];

/* Non-commercial / prototype manufacturer ID. Nothing on the wire acts on it,
 * which matters when the rig is a shared USB bus. */
const MFR = 0x7D;

/* ==================== the generator, used by BOTH directions ==================== */

/* Body byte at index i. A 7-bit counter, so every byte names its own position
 * mod 128 — a missing run shifts everything after it and shows up immediately.
 * The aligned 00 00 00 at 60..62 is deliberate: it lands on a packet boundary
 * (the F0 + 2 header bytes are 3, so body offset 0 is aligned), which is
 * exactly the packet #355 used to drop. If that regresses, this run vanishes
 * and the first-bad offset is 60. */
function bodyByte(i) {
    if (i >= 60 && i <= 62) return 0x00;
    return i & 0x7F;
}

function buildMessage(nbody) {
    const m = [0xF0, MFR, 0x01];
    for (let i = 0; i < nbody; i++) m.push(bodyByte(i));
    m.push(0xF7);
    return m;
}

/* Flat 4-byte USB-MIDI packets, concatenated — what move_midi_external_send
 * actually takes. Not raw SysEx bytes; handing it those sends garbage. */
function packetize(bytes) {
    const out = [];
    let i = 0;
    while (i < bytes.length) {
        const remain = bytes.length - i;
        if (remain > 3)       { out.push(0x04, bytes[i], bytes[i + 1], bytes[i + 2]); i += 3; }
        else if (remain === 3){ out.push(0x07, bytes[i], bytes[i + 1], bytes[i + 2]); i += 3; }
        else if (remain === 2){ out.push(0x06, bytes[i], bytes[i + 1], 0);            i += 2; }
        else                  { out.push(0x05, bytes[i], 0, 0);                       i += 1; }
    }
    return out;
}

/* 8-to-7 packing, which the spec names and does not define.
 *
 * One MSB byte per group of up to 7, holding bit 7 of each of those bytes in
 * order, then the seven bytes with bit 7 cleared. Read off the Max patch on
 * the lines thread rather than guessed: its LED chunk is `0 6 15 127 0 0 36`
 * and its ring chunk `0 3 0 12 0 $1 0 0` -- a leading zero then <=7 bytes,
 * which is exactly this with every payload byte already under 0x80. That is
 * also what post 2's "leds msg need an additional leading 0" is describing.
 *
 * So for LABELS and LED RING the MSB byte is always 0 and the packing looks
 * like padding. It is not: FRAMEBUFFER carries real pixel bytes with bit 7
 * set, and a packer written to emit a constant zero would work on everything
 * here and corrupt the one message that matters. */
function pack7(raw) {
    const out = [];
    for (let i = 0; i < raw.length; i += 7) {
        const n = Math.min(7, raw.length - i);
        let msbs = 0;
        for (let k = 0; k < n; k++) if (raw[i + k] & 0x80) msbs |= (1 << k);
        out.push(msbs);
        for (let k = 0; k < n; k++) out.push(raw[i + k] & 0x7F);
    }
    return out;
}

/* F0 + header + 2-byte ID + packed payload + F7. */
function oxiMsg(id, raw) {
    return [0xF0].concat(OXI_HDR, id, pack7(raw), [0xF7]);
}

/* 16-char title then 16 four-char labels, space padded. Deliberately not all
 * the same string: a screen showing one repeated label proves the message
 * arrived and nothing about whether the 80 bytes landed in the right order. */
function labelsPayload() {
    const title = "SCHWUNG E16 TEST";           /* exactly 16 */
    const raw = [];
    for (let i = 0; i < 16; i++) raw.push(title.charCodeAt(i));
    for (let i = 1; i <= 16; i++) {
        const t = (i < 10 ? "Enc" + i : "En" + i);   /* 4 chars either way */
        for (let k = 0; k < 4; k++) raw.push(t.charCodeAt(k));
    }
    return raw;
}

/* The ring amount is "a 14-bit value mapping to 0-100%", which is two claims
 * that cannot both be the encoding, and the Max patch votes for the second:
 * it fed `random 100` into the LSB alone and called the result working.
 *
 * So this does not pick one. Encoders 1-8 ramp across 0-100 and 9-16 ramp
 * across 0-16383, in two different colours. Whichever half is a ramp on the
 * hardware is the scale, and the other half will be flat -- one press answers
 * it, where sending a single guessed value would leave "it looked wrong"
 * pointing at the packing, the header, or the scale with no way to separate
 * them. */
function ringPayload() {
    const raw = [];
    for (let i = 0; i < 16; i++) {
        const pct = i < 8;
        const amt = pct ? Math.round(100 * i / 7)
                        : Math.round(16383 * (i - 7) / 8);
        raw.push(i);                                  /* encoder index 0-15 */
        raw.push(pct ? 0 : 60);                       /* R */
        raw.push(pct ? 60 : 0);                       /* G */
        raw.push(0);                                  /* B */
        raw.push((amt >> 7) & 0x7F);                  /* amount MSB */
        raw.push(amt & 0x7F);                         /* amount LSB */
        raw.push(0);                                  /* bipolar off */
    }
    return raw;
}

/* Parse a hex string into bytes. Returns {bytes, error}.
 *
 * Reports WHY it failed rather than sending something wrong: a message that is
 * silently truncated at the first bad token is exactly the failure mode this
 * whole module exists to find, and it would be absurd to reproduce it here.
 * Anything > 0xFF is rejected too -- that is almost always a missing space
 * between two bytes, which would otherwise sail through as one wrong value. */
function parseHex(text) {
    const cleaned = String(text).replace(/#[^\n]*/g, " ");
    const toks = cleaned.split(/[\s,]+/).filter(t => t.length > 0);
    const out = [];
    for (const t of toks) {
        const h = t.replace(/^0[xX]/, "");
        if (!/^[0-9a-fA-F]{1,2}$/.test(h)) {
            return { bytes: null, error: "bad token " + t.slice(0, 6) };
        }
        out.push(parseInt(h, 16));
    }
    if (out.length === 0) return { bytes: null, error: "file is empty" };
    return { bytes: out, error: null };
}

/* ==================== state ==================== */

let sizeIdx = 1;                  /* 158 bytes */
let txBytes = 0, txPackets = 0, txRefused = 0;
let rxBytes = 0, rxExpected = 0, rxFirstBad = -1, rxVerdict = "-";
let rxMessages = 0;
let customNote = "";
let lastVoice = "";       /* last channel-voice message seen from the E16 */
let oxiState = "";        /* what the E16 pad last did / saw */
let oxiSentAt = 0;
let ticks = 0;

/* Inbound assembler. onMidiMessageExternal hands over three bytes at a time
 * with the CIN ALREADY STRIPPED, so there is no length field to trust — the
 * trailing bytes of an end-packet are padding. F7 is the only terminator. */
let asm = null;

function rxByte(b) {
    if (b === 0xF0) { asm = []; return; }
    if (asm === null) return;
    if (b === 0xF7) { finishMessage(); asm = null; return; }
    /* Realtime (F8..FF) legitimately interleaves mid-SysEx and is not ours. */
    if (b >= 0xF8) return;
    /* Any other status byte means our message was interrupted; splicing what
     * follows onto it would produce a plausible-looking third message. */
    if (b >= 0x80) { asm = null; return; }
    if (asm.length < 4096) asm.push(b);
}

/* Is this assembled message the E16's remote-mode ACK?
 * `asm` holds everything between F0 and F7, so header then message ID. */
function isOxiAck() {
    if (asm.length !== OXI_HDR.length + OXI_ACK_ID.length) return false;
    for (let i = 0; i < OXI_HDR.length; i++) {
        if (asm[i] !== OXI_HDR[i]) return false;
    }
    return asm[OXI_HDR.length] === OXI_ACK_ID[0] &&
           asm[OXI_HDR.length + 1] === OXI_ACK_ID[1];
}

function finishMessage() {
    rxMessages++;

    if (isOxiAck()) {
        oxiState = "E16 ACK! remote on";
        return;   /* not one of ours to score against the generator */
    }
    /* asm holds MFR, 0x01, then the body. */
    const body = asm.slice(2);
    rxBytes = asm.length + 2;                 /* + F0 F7, for a wire-byte count */
    rxFirstBad = -1;
    for (let i = 0; i < body.length; i++) {
        if (body[i] !== bodyByte(i)) { rxFirstBad = i; break; }
    }
    /* We do not know which size the sender chose, so score against the nearest
     * declared size rather than inventing one. */
    rxExpected = 0;
    for (const s of SIZES) if (Math.abs(s - body.length) < Math.abs(rxExpected - body.length)) rxExpected = s;

    if (rxFirstBad < 0 && body.length === rxExpected) rxVerdict = "INTACT";
    else if (rxFirstBad < 0) rxVerdict = "SHORT-TAIL";
    else rxVerdict = (rxFirstBad % 3 === 0) ? "LOST PKTS" : "CORRUPT";
}

/* ==================== send ==================== */

function sendOne() {
    const msg = buildMessage(SIZES[sizeIdx]);
    const pkts = packetize(msg);
    txBytes = msg.length;
    txPackets = pkts.length / 4;
    txRefused = 0;

    /* ONE call, deliberately. Pacing it here would hide the very thing under
     * test: whether the host carries a burst it cannot place in one frame, or
     * silently discards the tail. A module author writing an editor sends the
     * whole dump and moves on, so that is what gets measured. */
    const ok = move_midi_external_send(pkts);
    if (!ok) txRefused = 1;
}

/* Send the file's contents verbatim. The point is that nothing here
 * interprets the message -- no framing check, no manufacturer-ID guess, no
 * "helpfully" adding F0/F7. If the bytes are wrong, that is a fact about the
 * bytes, and the shim's PRE tap will still show exactly what went to MIDI_OUT.
 */
function sendOxi(msg, label) {
    customNote = "";
    const pkts = packetize(msg);
    txBytes = msg.length;
    txPackets = pkts.length / 4;
    txRefused = move_midi_external_send(pkts) ? 0 : 1;
    if (txRefused) {
        oxiState = label + " REFUSED";
    } else {
        /* Deliberately not "sent OK" -- the send returning true only means the
         * host queued it. Whether the E16 got it is the ACK's job to say. */
        oxiState = label + " sent, waiting ACK";
        oxiSentAt = ticks;
    }
}

/* RAW mode: the file names the PACKETS, CIN byte and all.
 *
 * Everything this module has been used for in the last hour varies ONE thing --
 * the CIN nibble -- and every variation cost a cross-compile, a reinstall and a
 * reboot. That is the wrong loop for a question this small, and it is the
 * module's own fault: pad 5 could already send arbitrary bytes, but it ran them
 * through packetize(), which chooses the CINs. The file could say anything
 * except the thing under test.
 *
 * With `RAW` as the first token the remaining bytes go to the wire verbatim, in
 * 4-byte groups. So a new hypothesis is now an ssh and a pad press:
 *
 *   echo 'RAW 06 F0 00 00  06 21 5B 00  06 02 01 00' > /data/UserData/schwung/sysex_send.txt
 *
 * The count must be a multiple of 4, and a bad count is REPORTED rather than
 * rounded off -- a silently truncated final packet would look exactly like the
 * transport fault we are chasing.
 *
 * (No Linux-side alternative exists: Move's kernel has no ALSA at all and
 * devices on USB-A never enumerate in Linux -- see #358 -- so the SPI mailbox
 * is the only route to that port and a module is the only thing that can drive
 * it.) */
function sendCustom() {
    if (typeof host_file_exists === "function" && !host_file_exists(CUSTOM_PATH)) {
        customNote = "no file";
        txBytes = txPackets = 0;
        return;
    }
    const text = host_read_file(CUSTOM_PATH);
    if (text === null || text === undefined) {
        customNote = "unreadable";
        txBytes = txPackets = 0;
        return;
    }
    const raw = /^\s*RAW\b/i.test(text);
    const parsed = parseHex(raw ? text.replace(/^\s*RAW\b/i, " ") : text);
    if (!parsed.bytes) {
        customNote = parsed.error;
        txBytes = txPackets = 0;
        return;
    }

    let pkts;
    if (raw) {
        if (parsed.bytes.length % 4 !== 0) {
            customNote = "RAW len " + parsed.bytes.length + " %4!=0";
            txBytes = txPackets = 0;
            return;
        }
        pkts = parsed.bytes;
    } else {
        pkts = packetize(parsed.bytes);
    }

    txBytes = raw ? parsed.bytes.length : parsed.bytes.length;
    txPackets = pkts.length / 4;
    txRefused = move_midi_external_send(pkts) ? 0 : 1;
    customNote = (raw ? "RAW " : "sent ") + txPackets + "p" + (txRefused ? " REFUSED" : "");
    /* A raw send may well be a SysEx expecting a reply, so arm the ACK timer
     * exactly as the built-in E16 pads do -- otherwise row 3 keeps whatever the
     * last pad left there and reads as this send's result. */
    oxiState = "RAW " + txPackets + "p sent, waiting ACK";
    oxiSentAt = ticks;
}

/* ==================== lifecycle ==================== */

let ledInitPending = true;
let ledInitIndex = 0;

globalThis.init = function () {
    ledInitPending = true;
    ledInitIndex = 0;
};

function setupLedBatch() {
    for (let n = 0; n < 8 && ledInitIndex < 64; n++, ledInitIndex++) {
        const note = 68 + ledInitIndex;
        const isSize = PADS.indexOf(note) >= 0;
        if (note === CUSTOM_PAD || note === OXI_PAD || note === OXI_EXIT_PAD)
            setLED(note, DullGreen);
        else setLED(note, isSize ? (PADS[sizeIdx] === note ? DullGreen : DarkGreen) : Black);
    }
    if (ledInitIndex >= 64) ledInitPending = false;
}

function refreshSizeLeds() {
    for (let i = 0; i < PADS.length; i++) {
        setLED(PADS[i], i === sizeIdx ? DullGreen : DarkGreen);
    }
}

globalThis.onMidiMessageInternal = function (data) {
    if (shouldFilterMessage(data)) return;
    const status = data[0] & 0xF0;
    const d1 = data[1], d2 = data[2];

    if (status === 0x90 && d2 > 0) {
        const idx = PADS.indexOf(d1);
        if (idx >= 0) { sizeIdx = idx; refreshSizeLeds(); return; }
        if (d1 === CUSTOM_PAD) { sendCustom(); return; }
        if (d1 === OXI_PAD) { sendOxi(OXI_ENTER, "ENTER"); return; }
        if (d1 === OXI_EXIT_PAD) { sendOxi(OXI_EXIT, "EXIT"); return; }
        if (d1 === OXI_LABELS_PAD) {
            sendOxi(oxiMsg(OXI_ID_LABELS, labelsPayload()), "LABELS");
            return;
        }
        if (d1 === OXI_RING_PAD) {
            sendOxi(oxiMsg(OXI_ID_RING, ringPayload()), "RING");
            return;
        }
        if (d1 === PC_PAD) {
            /* Channel 1. Cycles so a repeat press is visibly a NEW scene --
             * sending the same program twice looks identical to nothing
             * happening, which is the ambiguity this whole module exists to
             * remove. CIN 0x0C is Program Change, two data bytes on the wire
             * with the third ignored. */
            const ok = move_midi_external_send([0x0C, 0xC0, pcProgram & 0x0F, 0x00]);
            oxiState = "PC " + ((pcProgram & 0x0F) + 1) + (ok ? " sent" : " REFUSED");
            pcProgram++;
            txBytes = 2; txPackets = 1; txRefused = ok ? 0 : 1;
            oxiSentAt = 0;              /* no ACK is expected for a PC */
            return;
        }
        if (d1 === CC_PAD) {
            const ok = move_midi_external_send([0x0B, 0xB0, 0x01, 0x40]);
            oxiState = "CC1=64 " + (ok ? "sent" : "REFUSED");
            txBytes = 3; txPackets = 1; txRefused = ok ? 0 : 1;
            oxiSentAt = 0;
            return;
        }
        if (d1 === OXI_ENTER_F_PAD) {
            sendOxiSingle(OXI_ENTER, "ENTER/0F");
            return;
        }
        if (d1 === OXI_LABELS_F_PAD) {
            sendOxiSingle(oxiMsg(OXI_ID_LABELS, labelsPayload()), "LBL/0F");
            return;
        }
        if (d1 === OXI_ENTER_7_PAD) {
            /* ENTER is 9 bytes -- already a multiple of 3, no padding needed. */
            sendOxiAllEnds(OXI_ENTER, "ENTER/07");
            return;
        }
        if (d1 === OXI_PROBE_PAD) {
            /* F0 F7: a legal empty SysEx in ONE CIN 0x06 packet. No 0x04. */
            const ok = move_midi_external_send([0x06, 0xF0, 0xF7, 0x00]);
            oxiState = "probe F0F7 " + (ok ? "sent" : "REFUSED");
            txBytes = 2; txPackets = 1; txRefused = ok ? 0 : 1;
            oxiSentAt = 0;
            return;
        }
        /* Any other pad sends the generated payload. */
        if (d1 > OXI_PROBE_PAD && d1 <= 99) { customNote = ""; sendOne(); }
    }
};

globalThis.onMidiMessageExternal = function (data) {
    /* Channel-voice traffic, reported because it is the one confirmation that
     * does not depend on the ACK reaching us. In remote mode the E16's turns
     * are FIXED: CC 1-16 on channel 1, relative and accelerated (0x01..0x08 /
     * 0x7F..0x78), buttons are notes 0-15 and Shift is note 16, whatever scene
     * the user is on. Out of remote mode the scene decides, so a button press
     * arriving as note 0 on channel 1 says remote mode engaged even if nothing
     * came back on the SysEx path.
     *
     * Guarded on asm === null so a payload byte can never be read as a status:
     * inside a SysEx every byte is < 0x80 by construction. */
    const st = data[0];
    if (asm === null && st >= 0x80 && st < 0xF0) {
        const type = st & 0xF0, ch = (st & 0x0F) + 1;
        const kind = type === 0xB0 ? "cc" : (type === 0x90 ? "on" : (type === 0x80 ? "off" : "0x" + type.toString(16)));
        lastVoice = kind + " " + data[1] + "=" + data[2] + " ch" + ch;
    }

    /* Three bytes, CIN stripped. Feed all three; the assembler ignores the
     * padding an end-packet carries. */
    rxByte(data[0]); rxByte(data[1]); rxByte(data[2]);
};

globalThis.tick = function () {
    ticks++;
    /* An ACK that never arrives has to say so. Without a timeout the screen
     * would sit on "waiting ACK" forever, which reads as "still working" --
     * the same ambiguity between slow and broken that made the outbound bug
     * take so long to find. ~2 s at the ~44 Hz tick. */
    if (oxiSentAt && (ticks - oxiSentAt) > 88) {
        oxiState = oxiState.replace(" waiting ACK", " NO ACK (2s)");
        oxiSentAt = 0;
    }
    if (ledInitPending) { setupLedBatch(); return; }
    draw();
};

function draw() {
    clear_screen();
    print(2, 0, "SysEx Test", 2);
    draw_line(0, 13, 127, 13, 1);

    /* FIVE rows fit between the rule and the footer at a 10px pitch, and the
     * first version printed six -- oxiState over the rx line and customNote
     * over the verdict, both at the same y. The pair that collided were the
     * two the E16 test reads, so the screen looked like the tool had simply
     * not noticed the press. */
    print(2, 16, "sz" + SIZES[sizeIdx] + " tx" + txBytes + "B/" + txPackets + "p" +
                        (txRefused ? " REFUSED" : ""), 1);
    print(2, 26, "rx " + rxBytes + "B n=" + rxMessages + " " + rxVerdict +
                        (rxFirstBad >= 0 ? "@" + rxFirstBad : ""), 1);
    print(2, 36, oxiState || "-", 1);
    print(2, 46, lastVoice || customNote || "-", 1);

    print(2, 56, "6on 11cc 12=0F 14=07 15pr", 1);
}
